### ISSUE TITLE
Control Pilot Signal to PLC jumpers

### ISSUE THREAD

**Issue by brandonprry** [PionixPublic/reference-hardware#9]
If powering the Yak board via the 12v power supply separate from the Yeti, how should I connect a control pilot signal to the PLC jumpers on the board for ISO15118 communication?

Please let me know if this question doesn't make sense.

**Comment by corneliusclaussen** [comment]
Not sure how your setup looks like. Are you using a yeti or not? In case you only use the yak you will need to have a CP generator externally that creates the pwm (and implements the evse_board_support in Everest), that yak only has the PLC modem and it is connected to the CP signal on the 10 pin connector.

**Comment by brandonprry** [comment]
Thanks for the response.

I'm currently experimenting with an ISO15118-20-enabled EVSE and simulating an electric vehicle with the Fluke FEV100. The FEV100 exposes the Control Pilot and I'm attempting to use the Yak separate from the Yeti to perform the EV-side of the V2G communication.

I'm not 100% sure this will work, but I don't see a reason it shouldn't work. I'll test with the J10 pin as soon as possible.

EDIT: I think misread. You said the 10-pin connector. However, there are 3 PLC jumpers (J9, J10, and J11). If I'm powering the Yak separately via the 12v power instead of the 10-pin connector through the Yeti, what would the configuration be to pass the control pilot from the FEV100 to the PLC jumpers on the board that are separate from the 10-pin connector.

**Comment by brandonprry** [comment]
Or should I power the Yak via the 12v port then connect to the pin for the Control Pilot in the 10-pin connector?

**Comment by corneliusclaussen** [comment]
It does not matter where the 12v are coming from, but the GND of the power needs to connect to PE of the charging cable for plc to work. The yeti/yak is not for ev side so it does not contain the CP circuitry for the EV side, so this will not work in principle. You can however switch to state B on the fluke simulator and you will get at least to cablecheck. Once you are there you will need to switch at the correct timing to state C to go further. The PLC on yak is for evse side. You can reconfigure it for ev side using the openplc utils (download pib file, patch with pev.sh, reflash pib). Then create an Everest config for ev side with ev alac etc. It is quite a bit of hacking and not an application that yak was designed for. Also the Qualcomm modems freeze quite frequently on ev side and yak does not have the reset pin wired out.

**Comment by brandonprry** [comment]
Perfect, thanks so much.

**Comment by corneliusclaussen** [comment]
The CP is connected from Fluke to CP on the 10pin connector on yak. There is only one 10pin connector that normally connects to yeti. Yak will add the PLC signal to the CP wire.
